### ISSUE TITLE
Chapter 7.4: Snippet  introduced as an example of RPITIT but it is instead just RPIT?

### ISSUE THREAD

**Issue by abigagli** [QuineDot/rust-learning#6]
At the beginning of the [7.4](https://quinedot.github.io/rust-learning/m-rpitit-alikes.html), after the async example, the following snippet is introduced as an example of RPITIT
```
impl MyStruct {
    fn iter(&self) -> impl Iterator<Item = String> {
        ["Hi :-)"].into_iter().map(ToString::to_string)
    }
}
```

but isn't it just an inherent method of a struct and hence a case of "normal" RPIT (no trait in sight here)??

I think the snippet should be
```
struct MyStruct;
trait MyTrait
{
   fn iter(&self) -> impl Iterator<Item = String> {
        ["Hi :-)"].into_iter().map(ToString::to_string)
    }
}
impl MyTrait for MyStruct {}
```

**Comment by QuineDot** [comment]
Yes, good catch.
